spring:
    datasource:
        url: jdbc:h2:mem:zooplus;DB_CLOSE_DELAY=-1
        name:
        username: zooplus
        password:
    h2:
        console:
            enabled: true
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create
        show_sql: true
    thymeleaf:
        cache: false
server:
    port: 80
